# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  alpine-3:
    # Base OS
    runs-on: ubuntu-latest
    # Docker Image
    container:
      image: alpine:3
    env:
      working-directory: ./alpine
    steps:
    - uses: actions/checkout@v2
    - name: Install bash
      run: apk add --no-cache bash
    - name: Make executable
      run: chmod +x *
      working-directory: ${{ env.working-directory }}
    - name: Install deps
      run: cat 3-deps.bash | bash
      working-directory: ${{ env.working-directory }}
    - name: Install user
      run: cat 3-user.bash | bash
      working-directory: ${{ env.working-directory }}

  debian-stretch-slim:
    # Base OS
    runs-on: ubuntu-latest
    # Docker Image
    container:
      image: debian:stretch-slim
    env:
      working-directory: ./debian
    steps:
    - uses: actions/checkout@v2
    - name: Make executable
      run: chmod +x *
      working-directory: ${{ env.working-directory }}
    - name: Install deps
      run: ./stretch-deps.bash
      working-directory: ${{ env.working-directory }}
    - name: Install user
      run: ./stretch-deps.bash
      working-directory: ${{ env.working-directory }}
