name: tagging
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      id: build_number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Create a Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.date.outputs.date }}.${{ steps.build_number.outputs.build_number }}
        release_name: ${{ steps.date.outputs.date }}.${{ steps.build_number.outputs.build_number }}
